USE [master]
GO

/****** Object:  Database [DB_RAMP_BUFF]    Script Date: 4/24/2026 4:06:16 PM ******/
CREATE DATABASE [DB_RAMP_BUFF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_RAMP_BUFF', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DB_RAMP_BUFF.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_RAMP_BUFF_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\DB_RAMP_BUFF_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_RAMP_BUFF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_RAMP_BUFF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET  MULTI_USER 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_RAMP_BUFF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_RAMP_BUFF] SET QUERY_STORE = OFF
GO

USE [DB_RAMP_BUFF]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DB_RAMP_BUFF] SET  READ_WRITE 
GO


